// Pure-frontend export helpers — turns a VideoDetail into Markdown/JSON
// and triggers a browser download. No backend involvement.

import type { VideoDetail } from "@/lib/api";
import { formatTimestamp } from "@/lib/utils";

/* ── Filename helper ─────────────────────────────────────────── */

function slugify(s: string, fallback = "vidiq-export"): string {
  const slug = s
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 80);
  return slug || fallback;
}

/* ── Markdown serialiser ─────────────────────────────────────── */

export function videoToMarkdown(video: VideoDetail): string {
  const out: string[] = [];
  const title = video.title || "Untitled video";

  out.push(`# ${title}`);
  out.push("");
  out.push(`> Generated by VidIQ on ${new Date().toISOString().split("T")[0]}`);
  out.push("");

  // ── Metadata block ────────────────────────────────────────
  out.push(`**Source:** ${video.source_url}`);
  if (video.channel) out.push(`**Channel:** ${video.channel}`);
  if (video.duration_sec)
    out.push(`**Duration:** ${formatTimestamp(video.duration_sec)}`);
  out.push(`**Source type:** ${video.source_type}`);
  out.push(`**Created:** ${new Date(video.created_at).toLocaleString()}`);
  out.push("");

  const s = video.summary;
  if (s) {
    out.push("---");
    out.push("");
    out.push("## Overview");
    out.push("");
    out.push(s.overview);
    out.push("");

    if (s.sentiment) {
      out.push(`**Sentiment:** ${s.sentiment}`);
      out.push("");
    }

    if (s.topics?.length) {
      out.push(`**Topics:** ${s.topics.join(", ")}`);
      out.push("");
    }

    if (s.key_points?.length) {
      out.push("## Key takeaways");
      out.push("");
      s.key_points.forEach((kp, i) => out.push(`${i + 1}. ${kp}`));
      out.push("");
    }

    if (s.chapters?.length) {
      out.push("## Chapters");
      out.push("");
      s.chapters.forEach((c) => {
        out.push(`- **[${formatTimestamp(c.start)}]** ${c.title}`);
      });
      out.push("");
    }

    if (s.pseudocode) {
      out.push("## Pseudocode");
      out.push("");
      out.push("```");
      out.push(s.pseudocode);
      out.push("```");
      out.push("");
    }
  }

  if (video.events?.length) {
    out.push("---");
    out.push("");
    out.push("## Events");
    out.push("");
    video.events.forEach((e) => {
      const sev = e.severity ? ` _(${e.severity})_` : "";
      out.push(`### [${formatTimestamp(e.timestamp)}] ${e.title}${sev}`);
      if (e.category) out.push(`*Category:* ${e.category}`);
      out.push("");
      out.push(e.description);
      out.push("");
    });
  }

  if (video.keyframes?.length) {
    out.push("---");
    out.push("");
    out.push(`## Keyframes (${video.keyframes.length})`);
    out.push("");
    video.keyframes.forEach((k) => {
      const cap = k.caption || "(no caption)";
      out.push(`- **[${formatTimestamp(k.timestamp)}]** ${cap}`);
    });
    out.push("");
  }

  if (video.transcript?.length) {
    out.push("---");
    out.push("");
    out.push(`## Transcript (${video.transcript.length} segments)`);
    out.push("");
    video.transcript.forEach((seg) => {
      const speaker = seg.speaker ? `**${seg.speaker}:** ` : "";
      out.push(`**[${formatTimestamp(seg.start)}]** ${speaker}${seg.text}`);
      out.push("");
    });
  }

  out.push("---");
  out.push("");
  out.push(
    `_Exported from VidIQ — analysis ${video.id}. ${video.transcript?.length ?? 0} transcript segments · ${video.keyframes?.length ?? 0} keyframes · ${video.events?.length ?? 0} events._`,
  );

  return out.join("\n");
}

/* ── JSON serialiser (raw structured export) ─────────────────── */

export function videoToJson(video: VideoDetail): string {
  const payload = {
    exported_at: new Date().toISOString(),
    exported_by: "vidiq",
    video,
  };
  return JSON.stringify(payload, null, 2);
}

/* ── Browser download trigger ────────────────────────────────── */

export function downloadFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Free the object URL on the next tick (Firefox needs the small delay).
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

export function downloadVideoMarkdown(video: VideoDetail) {
  const md = videoToMarkdown(video);
  downloadFile(`${slugify(video.title || video.id)}.md`, md, "text/markdown");
}

export function downloadVideoJson(video: VideoDetail) {
  const json = videoToJson(video);
  downloadFile(`${slugify(video.title || video.id)}.json`, json, "application/json");
}
